# Netlify configuration for Vite + Functions

[build]
  # Always install deps explicitly to ensure devDependencies (like Vite) are present
  command = "npm ci && npm run build"
  publish = "dist"       # public/_redirects will be copied here by Vite
  functions = "netlify/functions"

[build.environment]
  # Use a modern Node and make sure devDependencies are installed (no --production)
  NODE_VERSION = "20"
  NPM_FLAGS = ""

[dev]
  command = "npm run dev"          # Start Vite dev server
  targetPort = 5173                 # Vite dev server port
  port = 8888                       # Netlify Dev proxy port
  framework = "vite"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"         # Better ESM support

# Do not define SPA fallback here; we use public/_redirects for redirects and headers.
